// eslint-disable-next-line no-shadow
export enum WebsocketEventsEnum {
  TRANSACTION_ACCEPTED = 'TRANSACTION_ACCEPTED',
  TRANSACTION_SUBMITTED = 'TRANSACTION_SUBMITTED',
  TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  EXCHANGE_RATE_UPDATED = 'EXCHANGE_RATE_UPDATED',
  NOTIFICATION = 'NOTIFICATION',
}
