export enum OnOffRampStatusesEnum {
  DRAFT = 'DRAFT',
  INITIATED = 'INITIATED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  DECLINED = 'DECLINED',
  CANCELLED = 'CANCELLED',
}
