root: true
env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
settings:
  import/resolver: typescript
rules:
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/no-explicit-any": off
  import/extensions: off
  import/prefer-default-export: off
  import/no-extraneous-dependencies: off
  no-param-reassign: off
  no-useless-constructor: off
  no-plusplus: off
  no-nested-ternary: off
  no-return-assign: off
  no-continue: off
  consistent-return: off
  class-methods-use-this: warn
  no-shadow: warn
  no-await-in-loop: warn
  no-restricted-syntax:
    - error
    - WithStatement
  prettier/prettier:
    - error
    - endOfLine: auto
      printWidth: 120
      tabWidth: 2
      useTabs: false
      trailingComma: all
      singleQuote: true
      semi: true
  max-len:
    - error
    - code: 120
      ignoreStrings: true
