export enum MerchantLogActionEnum {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DISABLED = 'DISABLED',
  ENABLED = 'ENABLED',
  DELETED = 'DELETED',
  OPERATOR_CREATED = 'OPERATOR_CREATED',
  OPERATOR_DISABLED = 'OPERATOR_DISABLED',
  OPERATOR_ENABLED = 'OPERATOR_ENABLED',
  OPERATOR_DELETED = 'OPERATOR_DELETED',
}
