export enum ServicesEnum {
  TRANSACTION_SERVICE = 'TRANSACTION_SERVICE',
  PAYMENT_GATEWAY_API = 'PAYMENT_GATEWAY_API',
  RATE_SERVICE = 'RATE_SERVICE',
  WHITELABEL_API = 'WHITELABEL_API',
  KYC_SERVICE = 'KYC_SERVICE',
  MOBILE_API = 'MOBILE_API',
  ON_OFF_RAMP = 'ON_OFF_RAMP',
  TRAFFIC_PROTECTION_ENGINE = 'TRAFFIC_PROTECTION_ENGINE',
}
