export enum AmlStatusReasonEnum {
  BYPASSED_BY_ON_OF_RAMP = 'BYPASSED_BY_ON_OF_RAMP',
  BYPASSED_BY_DEV_ENV = 'BYPASSED_BY_DEV_ENV',
  BYPASSED_BY_ADMIN = 'BYPASSED_BY_ADMIN',
  BYPASSED_BY_SAME_WALLET_REFUND = 'BYPASSED_BY_SAME_WALLET_REFUND',
  BYPASSED_BY_NOT_EXISTING_WALLET = 'BYPASSED_BY_NOT_EXISTING_WALLET',
  BYPASSED_BY_UNRECOGNISED_ASSET = 'BYPASSED_BY_UNRECOGNISED_ASSET',
  // Fireblocks values
  BYPASSED_BY_POLICY = 'BYPASSED_BY_POLICY',
  BYPASSED_BY_UNSUPPORTED_ASSET = 'BYPASSED_BY_UNSUPPORTED_ASSET',
  BYPASSED_BY_UNSUPPORTED_ROUTE = 'BYPASSED_BY_UNSUPPORTED_ROUTE',
  BYPASSED_BY_FAILURE = 'BYPASSED_BY_FAILURE',
  BYPASSED_BY_MANUAL = 'BYPASSED_BY_MANUAL',
}
