export enum InitiatorTypeEnum {
  MERCHANT_USER = 'MERCHANT_USER',
  MERCHANT = 'MERCHANT',
  WEBHOOK = 'WEBHOOK',
  ELLIPTIC = 'ELLIPTIC',
  CHAIN_ANALYSIS = 'CHAIN_ANALYSIS',
  ADMIN = 'ADMIN',
  MERCHANT_OPERATOR = 'MERCHANT_OPERATOR',
  CUSTOMER = 'CUSTOMER',
  XCOINS = 'XCOINS',
  RATE_SERVICE = 'RATE_SERVICE',
  ON_OFF_RAMP = 'ON_OFF_RAMP',
}
