export enum TransactionLogEventEnum {
  CREATED = 'CREATED',
  UPDATED_MANUALLY = 'UPDATED_MANUALLY',
  UPDATED = 'UPDATED',
  ERROR = 'ERROR',
  MERCHANT_WEBHOOK = 'MERCHANT_WEBHOOK',
  INFO = 'INFO',
}
