export enum BlockchainEnum {
  ETHEREUM = 'ethereum',
  BITCOIN = 'bitcoin',
  DOGECOIN = 'dogecoin',
  RIPPLE = 'ripple',
  POLKADOT = 'polkadot',
  SOLANA = 'solana',
  LITECOIN = 'litecoin',
  BITCOIN_CASH = 'bitcoin-cash',
  MATIC = 'matic',
  TRON = 'tron',
  BINANCE_SMART_CHAIN = 'binance-smart-chain',
  BAHAMUT = 'bahamut',
  CARDANO = 'cardano',
}
