export enum CryptoEnum {
  BTC = 'BTC',
  LTC = 'LTC',
  BCH = 'BCH',
  ETH = 'ETH',
  MATIC = 'MATIC',
  USDT = 'USDT',
  DOGE = 'DOGE',
  XRP = 'XRP',
  DOT = 'DOT',
  DAI = 'DAI',
  SOL = 'SOL',
  USDC = 'USDC',
  BNB = 'BNB',
  TUSD = 'TUSD',
  BUSD = 'BUSD',
  TRX = 'TRX',
  FTN = 'FTN',
  USDTTR = 'USDTTR',
  ADA = 'ADA',
  SHIB = 'SHIB',
}
