import { AllCurrenciesEnum } from './all.currency.enum';
// import { AppLogger } from '../../../logs';

// const logger = new AppLogger('Currency id to code');

// NOTE update this map when adding new currencies
// Since the ids are constant for currencies and to skip the querying db for the code
const CurrencyIdToCodeMapper = new Map<number, AllCurrenciesEnum>([
  [10, AllCurrenciesEnum.USD],
  [11, AllCurrenciesEnum.EUR],
  [12, AllCurrenciesEnum.GBP],
  [13, AllCurrenciesEnum.BTC],
  [14, AllCurrenciesEnum.ETH],
  [15, AllCurrenciesEnum.MATIC],
  [16, AllCurrenciesEnum.DOGE],
  [17, AllCurrenciesEnum.XRP],
  [18, AllCurrenciesEnum.DOT],
  [19, AllCurrenciesEnum.SOL],
  [20, AllCurrenciesEnum.DAI],
  [21, AllCurrenciesEnum.USDT],
  [22, AllCurrenciesEnum.USDC],
  [23, AllCurrenciesEnum.LTC],
  [24, AllCurrenciesEnum.BCH],
  [25, AllCurrenciesEnum.CAD],
  [26, AllCurrenciesEnum.BRL],
  [27, AllCurrenciesEnum.NZD],
  [28, AllCurrenciesEnum.NOK],
  [29, AllCurrenciesEnum.PEN],
  [30, AllCurrenciesEnum.USDT],
  [31, AllCurrenciesEnum.TRX],
  [32, AllCurrenciesEnum.KRW],
  [33, AllCurrenciesEnum.AZN],
  [34, AllCurrenciesEnum.JPY],
  [35, AllCurrenciesEnum.CLP],
  [36, AllCurrenciesEnum.BDT],
  [37, AllCurrenciesEnum.THB],
  [38, AllCurrenciesEnum.BTC],
  [39, AllCurrenciesEnum.ETH],
  [40, AllCurrenciesEnum.USDT],
  [41, AllCurrenciesEnum.BNB],
  [42, AllCurrenciesEnum.BUSD],
  [43, AllCurrenciesEnum.TUSD],
  [45, AllCurrenciesEnum.MYR],
  [46, AllCurrenciesEnum.IDR],
  [47, AllCurrenciesEnum.VND],
  [48, AllCurrenciesEnum.PHP],
  [49, AllCurrenciesEnum.INR],
  [50, AllCurrenciesEnum.PLN],
  [51, AllCurrenciesEnum.SEK],
  [52, AllCurrenciesEnum.CHF],
  [53, AllCurrenciesEnum.AUD],
  [54, AllCurrenciesEnum.TRY],
  [55, AllCurrenciesEnum.AED],
  [56, AllCurrenciesEnum.DKK],
  [57, AllCurrenciesEnum.FTN],
  [58, AllCurrenciesEnum.ZAR],
  [59, AllCurrenciesEnum.COP],
  [60, AllCurrenciesEnum.CRC],
  [61, AllCurrenciesEnum.DOP],
  [62, AllCurrenciesEnum.ISK],
  [63, AllCurrenciesEnum.ILS],
  [64, AllCurrenciesEnum.SGD],
  [65, AllCurrenciesEnum.UAH],
  [66, AllCurrenciesEnum.TWD],
  [67, AllCurrenciesEnum.ADA],
  [68, AllCurrenciesEnum.SHIB],
]);
export function getCurrencyCodeById(currencyId: number): AllCurrenciesEnum {
  const currencyCode = CurrencyIdToCodeMapper.get(Number(currencyId));
  return currencyCode;
}
